"""Add message id to measurement and device event

Revision ID: ae41cb4ee18e
Revises:
Create Date: 2026-04-24 11:05:57.004972

"""

from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae41cb4ee18e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("device_event", sa.Column("message_id", sa.String(), nullable=True))
    op.add_column("measurement", sa.Column("message_id", sa.String(), nullable=True))

    connection = op.get_bind()
    device_event_table = table("device_event", column("id"), column("message_id"))
    measurement_table = table("measurement", column("id"), column("message_id"))

    for t in [device_event_table, measurement_table]:
        rows = connection.execute(sa.select(t.c.id)).fetchall()
        for row in rows:
            new_id = str(uuid.uuid4())
            connection.execute(
                t.update().where(t.c.id == row.id).values(message_id=new_id)
            )

    op.alter_column("device_event", "message_id", nullable=False)
    op.alter_column("measurement", "message_id", nullable=False)

    op.drop_table("temperaturemeasurement")
    op.drop_table("eventmodel")
    op.drop_table("devicestate")
    op.drop_table("humiditymeasurement")
    op.create_index(
        op.f("ix_device_event_message_id"), "device_event", ["message_id"], unique=True
    )
    op.drop_index(op.f("ix_measurement_device_id"), table_name="measurement")
    op.create_index(
        "ix_measurement_device_id",
        "measurement",
        ["peripheral_id", "event", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurement_message_id"), "measurement", ["message_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_measurement_message_id"), table_name="measurement")
    op.drop_index("ix_measurement_device_id", table_name="measurement")
    op.create_index(
        op.f("ix_measurement_device_id"),
        "measurement",
        ["device_id", "peripheral_id", "timestamp"],
        unique=False,
    )
    op.drop_column("measurement", "message_id")
    op.drop_index(op.f("ix_device_event_message_id"), table_name="device_event")
    op.drop_column("device_event", "message_id")
    op.create_table(
        "humiditymeasurement",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("sensor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("home_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("humiditymeasurement_pkey")),
    )
    op.create_table(
        "devicestate",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("home_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("devicestate_pkey")),
    )
    op.create_table(
        "eventmodel",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("event", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("peripheral_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("home_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("eventmodel_pkey")),
    )
    op.create_index(
        op.f("ix_event_device_id"),
        "eventmodel",
        ["device_id", "peripheral_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "temperaturemeasurement",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("sensor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("home_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("temperaturemeasurement_pkey")),
    )
    # ### end Alembic commands ###
